### ISSUE TITLE
Not parsing multi-line fields properly

### ISSUE THREAD

**Issue by Ziris85** [jelmer/deb822-lossless#26]
Hello! First of all, thank you for this crate - it's simplifying a project I'm working on a fair bit! However, I've noticed that the crate isn't properly able to parse files that have multi-line fields. In fact, the example provided on the main page fails to run successfully:
```
use deb822_lossless::Deb822;
use std::str::FromStr;

let input = r#"Package: deb822-lossless
Maintainer: Jelmer Vernooĳ <jelmer@debian.org>
Section: rust

Package: deb822-lossless
Architecture: any
Description: Lossless parser for deb822 style files.
  This parser can be used to parse files in the deb822 format, while preserving
  all whitespace and comments. It is based on the [rowan] library, which is a
  lossless parser library for Rust.

"#;

let deb822 = Deb822::from_str(input).unwrap();
assert_eq!(deb822.paragraphs().count(), 2);
```

Error is:
```
thread 'main' panicked at src/main.rs:23:5:
assertion `left == right` failed
  left: 3
 right: 2
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

If I remove the additional `Description` lines, the code parses.

**Comment by jelmer** [comment]
What version are you using? I can't reproduce this on either master or v0.1.8

**Comment by Ziris85** [comment]
Thanks for the reply! I was actually just injecting that code into another project I was working on, but if I put it into a clean codebase, while it's the same error, the counts change slightly. I'm using the latest version of this crate. Here's my main.rs:
```
use deb822_lossless::Deb822;
use std::str::FromStr;

fn main() {
    let input = r#"Package: deb822-lossless
    Maintainer: Jelmer Vernooĳ <jelmer@debian.org>
    Section: rust
    
    Package: deb822-lossless
    Architecture: any
    Description: Lossless parser for deb822 style files.
      This parser can be used to parse files in the deb822 format, while preserving
      all whitespace and comments. It is based on the [rowan] library, which is a
      lossless parser library for Rust.
    
    "#;
    
    let deb822 = Deb822::from_str(input).unwrap();
    assert_eq!(deb822.paragraphs().count(), 2);
}
```

And my cargo.toml
```
[package]
name = "rust_deb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deb822-lossless = "0.1.8"
```
Building and running this results in the following result:
```
]$ cargo run
   Compiling rust_deb v0.1.0 (/home/adam/Projects/RustDeb)
    Finished dev [unoptimized + debuginfo] target(s) in 0.11s
     Running `target/debug/rust_deb`
thread 'main' panicked at src/main.rs:19:5:
assertion `left == right` failed
  left: 1
 right: 2
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Ziris85** [comment]
OK, playing with it a bit more, I'm able to get it to compile. Apologies if these are rookie mistakes - far be it from me to claim to be very good here heh. I *do* have to get rid of the trailing whitespace to get it to work though - no permutation with that works for me. This, however, does:
```
use deb822_lossless::Deb822;
use std::str::FromStr;

fn main() {
    let input = r#"Package: deb822-lossless
Maintainer: Jelmer Vernooĳ <jelmer@debian.org>
Section: rust

Package: deb822-lossless
Architecture: any
Description: Lossless parser for deb822 style files.
  This parser can be used to parse files in the deb822 format, while preserving
  all whitespace and comments. It is based on the [rowan] library, which is a
  lossless parser library for Rust.
"#;
    
    let deb822 = Deb822::from_str(input).unwrap();
    assert_eq!(deb822.paragraphs().count(), 2);
}
```
